#!/usr/bin/env php
<?php

$command = $argv[1] ?? null;

switch ($command) {
    case 'run':
        $port = $argv[2] ?? 8888;

        echo "                _                ______                                           _    \n";
        echo "    /\         | |              |  ____|                                         | |   \n";
        echo "   /  \   _ __ | | _____  _ __  | |__ _ __ __ _ _ __ ___   _____      _____  _ __| | __\n";
        echo "  / /\ \ | '_ \| |/ / _ \| '__| |  __| '__/ _` | '_ ` _ \ / _ \ \ /\ / / _ \| '__| |/ /\n";
        echo " / ____ \| | | |   < (_) | |    | |  | | | (_| | | | | | |  __/\ V  V / (_) | |  |   < \n";
        echo "/_/    \_\_| |_|_|\_\___/|_|    |_|  |_|  \__,_|_| |_| |_|\___| \_/\_/ \___/|_|  |_|\_\'\n";
        echo "\n";
        echo "Starting server on http://localhost:$port\n";
        exec("php -S localhost:$port -t public");
        break;

    default:
        echo "Available commands:\n";
        echo "  run [port] - Start the development server (default: 8888)\n";
        break;
}
